DROP TABLE IF EXISTS DETALLE_FACTURA;
CREATE TABLE DETALLE_FACTURA (ID_DETALLE_FACTURA BIGINT PRIMARY KEY AUTO_INCREMENT, ID_FACTURA BIGINT, ID_PRODUCTO BIGINT,
CANTIDAD_PRODUCTOS BIGINT, TOTAL_PARCIAL BIGINT,


CONSTRAINT FK_DETFACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
CONSTRAINT FK_DETPRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)

);