DROP TABLE IF EXISTS EMPRESA;
CREATE TABLE EMPRESA ( id_Empresa bigint  PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(150),
direccion VARCHAR(150), rubro VARCHAR(150), dni_Empresa BIGINT, telefono  BIGINT);

