DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE ( id_Cliente BIGINT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(150) NOT NULL, apellido VARCHAR(150) NOT NULL,
dni BIGINT NOT NULL, direccion VARCHAR(150) NOT NULL, telefono  BIGINT);