DROP TABLE IF EXISTS FACTURA;
CREATE TABLE FACTURA (ID_FACTURA BIGINT PRIMARY KEY AUTO_INCREMENT, fecha_Emision DATE, tipo_Factura CHAR(1), total_Factura BIGINT,
 ID_CLIENTE BIGINT NOT NULL, ID_EMPRESA BIGINT NOT NULL,

 CONSTRAINT FK_FACCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
 CONSTRAINT FK_FACEMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
 );

